driverClassName=com.mysql.cj.jdbc.Driver
# ?????? url ????? &allowPublicKeyRetrieval=true
url=jdbc:mysql://localhost:3306/textbook?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
username=root
password=root
initialSize=5
maxActive=10
maxWait=3000